# Generated by Django 2.1.15 on 2021-11-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='文章')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='投稿日')),
            ],
            options={
                'verbose_name_plural': '記事',
            },
        ),
    ]
