# Generated by Django 2.1.15 on 2021-11-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_news', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
