# Generated by Django 2.1.15 on 2021-11-03 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_news', '0003_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='本文')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='投稿日')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='first_news.Article', verbose_name='記事')),
            ],
            options={
                'verbose_name_plural': 'コメント',
            },
        ),
    ]
