# Generated by Django 2.2.17 on 2021-11-04 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_news', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '記事'},
        ),
    ]
