# Generated by Django 2.2.17 on 2021-11-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_news', '0005_auto_20211104_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'コメント'},
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Some String', max_length=30, verbose_name='名前'),
        ),
    ]
