# Generated by Django 2.2.17 on 2021-11-09 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_news', '0007_auto_20211104_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '在庫管理'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '在庫管理2'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=100, null='消してね', verbose_name='商品名'),
            preserve_default='消してね',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=100, verbose_name='個数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='first_news.Article', verbose_name='記事'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=100, verbose_name='個数'),
        ),
    ]
